[package]
name = "derive_generic_visitor_macros"
version = "0.1.1"
edition = "2021"
description = "Macros for `derive_generic_visitor`"
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
darling = "0.20"
itertools = "0.13"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0.0", features = ["full"] }
